// Concise, checked HTML companion to section 7 and relevant section 8 tables.
// Each entry links back to the original PDF page for the full procedure or table.
export const readerEntries = [
  { id: 'owner-checks', group: 'Owner checks', title: 'Checks when refueling', page: 295, body: 'Check engine oil, coolant reservoir, washer fluid, and tires whenever you stop for fuel.', points: ['Look for low or underinflated tires.', 'Follow up promptly on adverse conditions.'], caution: 'Hot coolant and steam can cause serious burns. Do not open the cooling system while hot.' },
  { id: 'monthly-checks', group: 'Owner checks', title: 'Monthly checks', page: 296, body: 'Check coolant level, exterior lights, and inflation pressure for every tire, including the spare.', points: ['Check stoplights, turn signals, and hazard flashers.', 'Measure tire pressure when the tires are cold.'] },
  { id: 'seasonal-checks', group: 'Owner checks', title: 'Twice yearly checks', page: 296, body: 'In spring and fall, inspect hoses, washer and wiper operation, headlamp aim, exhaust parts, seat belts, tires, and lug nuts.', points: ['Clean wiper blades with washer fluid on a cloth.', 'Check for wear and proper operation of lap and shoulder belts.'] },
  { id: 'annual-checks', group: 'Owner checks', title: 'Yearly checks', page: 296, body: 'Clean body drains, lubricate hinges and latches, check the air conditioner, clean battery terminals, and check brake fluid.', points: ['The manual also calls for inspection and lubrication of automatic transaxle linkage and controls.'] },
  { id: 'choose-schedule', group: 'Schedules', title: 'Choose the correct schedule', page: 297, body: 'Use the normal schedule only if the vehicle is usually operated without the severe conditions described in the manual.', points: ['Repeated short trips, dusty or sandy roads, salt, mountains, extended idling, cold or humid operation, and heavy hot-weather city traffic can require the severe schedule.', 'Where mileage and time are both listed, use whichever comes first.'], caution: 'Continue the prescribed intervals beyond 150,000 miles or 120 months.' },
  { id: 'normal-7500', group: 'Schedules', title: 'Normal schedule: 7,500 miles or 6 months', page: 298, body: 'Rotate tires and inspect the battery, air cleaner filter, and vacuum hoses.', points: ['Replace engine oil and filter at the interval shown in the owner’s schedule.', 'The schedule includes fuel additive only under its stated fuel-quality condition.'], caution: 'The full table contains conditions and footnotes; consult the PDF before recording a service as complete.' },
  { id: 'normal-15000', group: 'Schedules', title: 'Normal schedule: 15,000 miles or 12 months', page: 298, body: 'Rotate tires and inspect major brake, steering, suspension, exhaust, driveline, battery, and air-conditioning items.', points: ['Replace the climate control air filter.', 'Inspect rear discs or drums only if equipped.', 'Replace oil and filter according to the stated mileage or time condition.'], caution: 'Use the source table for the complete item list and footnotes.' },
  { id: 'normal-later', group: 'Schedules', title: 'Continuing normal schedule', page: 301, body: 'The owner’s manual repeats the normal schedule through 150,000 miles or 120 months. Continue the prescribed intervals afterward.', points: ['At 60,000 miles or 48 months, the table includes air cleaner replacement and additional brake, fuel, steering, and drive-belt inspections.', 'Coolant replacement first appears at 60,000 miles or 60 months, then every 30,000 miles or 24 months.', 'Iridium spark plug replacement is listed at 105,000 miles or 84 months in the source table.'], caution: 'These examples do not replace the complete interval tables on PDF pages 298–307.' },
  { id: 'severe-schedule', group: 'Schedules', title: 'Severe-use intervals', page: 308, body: 'For qualifying severe use, replace engine oil and filter every 3,750 miles (6,000 km) or 6 months.', points: ['The table lists automatic transaxle fluid replacement every 60,000 miles for specified severe conditions and manual transaxle fluid every 75,000 miles for specified conditions.', 'Air cleaner, spark plugs, brakes, parking brake, steering, and cabin filter may need more frequent service depending on the condition.', 'The source page defines conditions A through K; match your usage to the table.'], caution: 'Do not apply a severe-use interval to a component without checking its listed driving-condition codes.' },
  { id: 'oil-check', group: 'Fluids and filters', title: 'Check and add engine oil', page: 312, body: 'The owner’s manual explains checking the level with the dipstick and adding oil if needed.', points: ['Use the specified oil grade and capacity on PDF pages 371–372.', 'After adding oil, recheck the level and avoid overfilling.'], caution: 'The radiator hose can be hot when checking or adding oil.' },
  { id: 'coolant-check', group: 'Fluids and filters', title: 'Check engine coolant', page: 313, body: 'Check the coolant level in the reservoir as described in the maintenance chapter.', points: ['The manual specifies ethylene glycol coolant suitable for an aluminum radiator.', 'Total capacity differs by transmission: automatic 6.23 US qt; manual 6.34 US qt.'], caution: 'Never remove the radiator cap while the engine is hot. Hot coolant can erupt under pressure.' },
  { id: 'brake-fluid', group: 'Fluids and filters', title: 'Brake and clutch fluid', page: 316, body: 'Check the reservoir level and use fluid meeting FMVSS116 DOT-3 or DOT-4.', points: ['The specification table gives approximately 0.7–0.8 US qt total capacity.', 'A low level can indicate wear or a leak and needs inspection.'], caution: 'Use only the specified fluid and keep it clean; follow the source cautions before opening the reservoir.' },
  { id: 'washer-parking', group: 'Fluids and filters', title: 'Washer fluid and parking brake', page: 317, body: 'Check the washer reservoir and parking-brake operation as described in the owner’s manual.', points: ['Use washer fluid appropriate for the climate.', 'Have a parking brake that does not hold correctly inspected.'], caution: 'Do not put radiator coolant or antifreeze in the washer-fluid reservoir.' },
  { id: 'air-filter', group: 'Fluids and filters', title: 'Engine air cleaner filter', page: 318, body: 'Open the air-cleaner cover, inspect the filter, and replace it when the schedule calls for replacement.', points: ['Wipe the housing clean before reinstalling the cover.', 'Dusty and sandy use may require more frequent replacement.'] },
  { id: 'cabin-filter', group: 'Fluids and filters', title: 'Climate control air filter', page: 319, body: 'The climate control filter is accessed behind the glove box. Follow the illustrated removal and installation sequence on PDF pages 319–320.', points: ['Replace it according to the normal or severe-use schedule.', 'Install the replacement in the direction shown by the manual.'] },
  { id: 'wipers', group: 'Visibility', title: 'Wiper blade replacement', page: 321, body: 'The manual describes blade replacement for the fitted front wiper type on PDF pages 321–323.', points: ['Clean contaminated blades and glass first.', 'Use the illustrated instructions for Type A or Type B as equipped.'], caution: 'Keep the wiper arm from snapping back against the windshield.' },
  { id: 'battery', group: 'Electrical', title: 'Battery inspection', page: 324, body: 'Inspect battery condition and terminals. The owner’s manual covers charging and items that may need resetting after battery disconnection on PDF pages 324–326.', points: ['Keep flames and sparks away from the battery.', 'Follow the manual’s charging and handling precautions.'], caution: 'Battery acid and gas can cause serious injury. Read the full warnings before service.' },
  { id: 'tires', group: 'Tires and wheels', title: 'Tire pressure and rotation', page: 327, body: 'Inspect tire condition and check inflation pressure at least monthly. The tire-and-wheel table lists 32 psi for the listed full-size tires under its stated load conditions.', points: ['The normal maintenance schedule calls for tire rotation at 7,500-mile intervals.', 'Wheel lug nut torque is 65–79 lb-ft (88–107 N·m).'], caution: 'Use the vehicle tire label and the manual’s tire-size and loading guidance for the fitted tires.' },
  { id: 'fuses', group: 'Electrical', title: 'Fuses and fuse panels', page: 340, body: 'The vehicle has an instrument-panel fuse panel and an engine-compartment fuse panel. The owner’s manual provides replacement instructions and panel charts on PDF pages 340–348.', points: ['Use the fuse rating specified for the circuit.', 'If a replacement fuse blows again, have the circuit inspected.'], caution: 'Do not substitute a higher-rated fuse or metal wire.' },
  { id: 'bulbs', group: 'Visibility', title: 'Bulb replacement', page: 349, body: 'The maintenance chapter illustrates replacement of exterior and interior lamps on PDF pages 349–357.', points: ['The bulb table on PDF page 369 lists H11 low beam, H1 high beam, 2357NA front signal, and W16W back-up bulb.', 'Front fog lamps are H27W if equipped.'], caution: 'Turn lamps off and follow the owner’s precautions; some lamp assemblies require professional service.' },
  { id: 'appearance', group: 'Care', title: 'Exterior and interior care', page: 358, body: 'The owner’s manual covers washing, waxing, underbody cleaning, corrosion prevention, and interior cleaning on PDF pages 358–363.', points: ['Rinse thoroughly after washing.', 'Pay special attention to underbody salt and corrosive deposits.'] },
  { id: 'emissions', group: 'Care', title: 'Emission controls', page: 364, body: 'The manual describes crankcase, evaporative, and exhaust-emission controls on PDF pages 364–366.', points: ['Follow the precautions for the catalytic converter and exhaust system.'], caution: 'Never operate the engine in a closed or poorly ventilated area; exhaust contains carbon monoxide.' },
  { id: 'lubricants', group: 'Specifications', title: 'Lubricants and capacities', page: 371, body: 'The specification table lists engine oil at 4.23 US qt for drain and refill; automatic transaxle fluid at 7.71 US qt total; and coolant at 6.23 US qt for automatic or 6.34 US qt for manual transaxle.', points: ['Automatic transaxle fluid must meet the listed SP-IV specification.', 'The oil viscosity chart on PDF page 372 recommends SAE 5W-20 for fuel economy and shows 5W-30 as an option.'], caution: 'A total fluid capacity is not the amount to pour into every drain-and-refill service.' },
  { id: 'bulb-table', group: 'Specifications', title: 'Bulb and wheel specifications', page: 369, body: 'The bulb table lists the fitted lamp types and wattages. The tire-and-wheel table on the next page lists tire sizes, pressures, and lug-nut torque.', points: ['Some listed lamps and equipment vary by trim.', 'Verify the fitted lamp assembly and tire label before buying parts.'] }
];
